# Generated by Django 3.0.2 on 2020-01-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='image',
            field=models.ImageField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
