# Generated by Django 3.0.2 on 2020-01-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200103_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='image',
            field=models.ImageField(upload_to='app/uploads/% Y/% m/% d/'),
        ),
    ]
