# Generated by Django 3.0.2 on 2020-01-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200103_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='image',
            field=models.ImageField(upload_to='app/uploads/2020/1/3/'),
        ),
    ]
