# Generated by Django 3.0.4 on 2020-04-02 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.TextField(unique=True)),
                ('media', models.TextField(blank=True, null=True)),
                ('preview', models.TextField(blank=True, null=True)),
                ('flair', models.CharField(blank=True, max_length=100, null=True)),
                ('is_self', models.BooleanField()),
                ('over_18', models.BooleanField()),
                ('subreddit', models.CharField(max_length=255)),
                ('score', models.PositiveIntegerField(default=0)),
                ('created', models.CharField(max_length=100)),
                ('created_utc', models.CharField(default='-', max_length=100)),
                ('url', models.URLField()),
                ('permalink', models.URLField()),
                ('thumbnail', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_posts', models.IntegerField()),
                ('failed_posts', models.IntegerField()),
                ('total_posts', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
