# Generated by Django 3.0.5 on 2020-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200508_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.FloatField(default=1594297880.021418),
        ),
    ]
