# Generated by Django 3.0.5 on 2020-05-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200521_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.FloatField(default=1590048849.924567),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.FloatField(default=1590048849.9242742),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created',
            field=models.FloatField(default=1590048849.924567),
        ),
    ]
