# Generated by Django 3.0.5 on 2020-06-29 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_auto_20200521_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.FloatField(default=1593422259.778262),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.FloatField(default=1593422259.7778418),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created',
            field=models.FloatField(default=1593422259.778262),
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.FloatField(default=1593422259.7778418)),
                ('modified', models.FloatField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('email_verification', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
