# Generated by Django 3.0.5 on 2020-06-29 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20200629_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.FloatField(default=1593422646.978196),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='created',
            field=models.FloatField(default=1593422646.977904),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.FloatField(default=1593422646.977904),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created',
            field=models.FloatField(default=1593422646.978196),
        ),
    ]
