# Generated by Django 3.0.5 on 2020-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200629_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='gender',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.FloatField(default=1594212623.486319),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='created',
            field=models.FloatField(default=1594212623.485893),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.FloatField(default=1594212623.485893),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created',
            field=models.FloatField(default=1594212623.486319),
        ),
    ]
