# Generated by Django 3.0.5 on 2020-07-09 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0008_auto_20200708_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.FloatField(default=1594297880.027155),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='created',
            field=models.FloatField(default=1594297880.026722),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.FloatField(default=1594297880.026722),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created',
            field=models.FloatField(default=1594297880.027155),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.FloatField(default=1594297880.026722)),
                ('modified', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
