# Generated by Django 2.2.6 on 2019-10-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='walletactivity',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
