export const CHECK_KEY_LOADING = 'CHECK_KEY_LOADING'
export const CHECK_KEY_SUCCESS = 'CHECK_KEY_SUCCESS'
export const CHECK_KEY_FAIL = 'CHECK_KEY_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'