module.exports = {
    PRODUCT_GET_LOADING: 'PRODUCT_GET_LOADING',
    PRODUCT_GET_SUCCESS: 'PRODUCT_GET_SUCCESS',
    PRODUCT_GET_FAIL: 'PRODUCT_GET_FAIL',
    CLEAR_PRODUCT_STATE: 'CLEAR_PRODUCT_STATE'
}