# Generated by Django 3.0.5 on 2020-05-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200509_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.FloatField(default=1589111699.2630417),
        ),
    ]
