# Generated by Django 3.0.5 on 2020-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200521_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.FloatField(default=1594297880.026722),
        ),
    ]
