# Generated by Django 3.0.5 on 2020-08-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200709_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.FloatField(default=1596433186.3020558),
        ),
    ]
