# Generated by Django 3.0.5 on 2020-08-03 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200803_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceinfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.FloatField(default=1596433750.5014),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.Product'),
        ),
    ]
