export const CURRENCIES_LOADING = 'CURRENCIES_LOADING'
export const CURRENCIES_SUCCESS = 'CURRENCIES_SUCCESS'
export const CURRENCIES_FAIL = 'CURRENCIES_FAIL'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const CHECK_AUTH_LOADING = 'CHECK_AUTH_LOADING'
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS'
export const CHECK_AUTH_FAIL = 'CHECK_AUTH_FAIL'

export const PUT_PROFILE_SETTINGS_LOADING = 'PUT_PROFILE_SETTINGS_LOADING'
export const PUT_PROFILE_SETTINGS_SUCCESS = 'PUT_PROFILE_SETTINGS_SUCCESS'
export const PUT_PROFILE_SETTINGS_FAIL = 'PUT_PROFILE_SETTINGS_FAIL'

export const GET_WALLET_LOADING = 'GET_WALLET'
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS'
export const GET_WALLET_FAIL = 'GET_WALLET_FAIL'

export const GET_WALLETACTIVITY_LOADING = 'GET_WALLETACTIVITY_LOADING'
export const GET_WALLETACTIVITY_SUCCESS = 'GET_WALLETACTIVITY_SUCCESS'
export const GET_WALLETACTIVITY_FAIL = 'GET_WALLETACTIVITY_FAIL'

export const POST_WALLETACTIVITY_LOADING = 'POST_WALLETACTIVITY_LOADING'
export const POST_WALLETACTIVITY_SUCCESS = 'POST_WALLETACTIVITY_SUCCESS'
export const POST_WALLETACTIVITY_FAIL = 'POST_WALLETACTIVITY_FAIL'

export const PUT_WALLETACTIVITY_LOADING = 'PUT_WALLETACTIVITY_LOADING'
export const PUT_WALLETACTIVITY_SUCCESS = 'PUT_WALLETACTIVITY_SUCCESS'
export const PUT_WALLETACTIVITY_FAIL = 'PUT_WALLETACTIVITY_FAIL'

export const DELETE_WALLETACTIVITY_LOADING = 'DELETE_WALLETACTIVITY_LOADING'
export const DELETE_WALLETACTIVITY_SUCCESS = 'DELETE_WALLETACTIVITY_SUCCESS'
export const DELETE_WALLETACTIVITY_FAIL = 'DELETE_WALLETACTIVITY_FAIL'

export const GET_CATEGORY_LOADING = 'GET_CATEGORY_LOADING'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL'

export const POST_CATEGORY_LOADING = 'POST_CATEGORY_LOADING'
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS'
export const POST_CATEGORY_FAIL = 'POST_CATEGORY_FAIL'

export const PUT_CATEGORY_LOADING = 'PUT_CATEGORY_LOADING'
export const PUT_CATEGORY_SUCCESS = 'PUT_CATEGORY_SUCCESS'
export const PUT_CATEGORY_FAIL = 'PUT_CATEGORY_FAIL'

export const TOP_LOADING = 'TOP_LOADING'
export const TOP_SUCCESS = 'TOP_SUCCESS'
export const TOP_FAIL = 'TOP_FAIL'

export const ALERT_SHOW = 'ALERT_SHOW'
export const ALERT_HIDE = 'ALERT_HIDE'
