export const GET_SCANS_LOADING = 'GET_SCANS_LOADING'
export const GET_SCANS_SUCCESS = 'GET_SCANS_SUCCESS'
export const GET_SCANS_FAIL = 'GET_SCANS_FAIL'

export const GET_SCANBYPK_LOADING = 'GET_SCANBYPK_LOADING'
export const GET_SCANBYPK_SUCCESS = 'GET_SCANBYPK_SUCCESS'
export const GET_SCANBYPK_FAIL = 'GET_SCANBYPK_FAIL'